export { default as IconCamera } from './camera.svg'
export { default as IconCompass } from './compass.svg'
export { default as IconHeart } from './heart.svg'
export { default as IconHome } from './home.svg'
export { default as IconMessages } from './messages.svg'
export { default as IconPlusSquare } from './plus-square.svg'
export { default as IconSearch } from './search.svg'
